### ISSUE TITLE
ctrl-c doesn't kill the node process

### ISSUE THREAD

**Issue by lookfirst** [pmb0/express-sharp#1]
Thanks for your project. I'm using it as a basis for one of my own (I have some unique requirements). =)

ctrl-c works if I just start up the server and don't use it. But, if I use it to render an image, I can't ctrl-c it. Nothing obvious stands out as to why that happens.

Thoughts?

**Comment by pmb0** [comment]
You should consider using a [process manager](http://expressjs.com/en/advanced/pm.html).
