### ISSUE TITLE
resize/num without height does not work

### ISSUE THREAD

**Issue by hefox** [pmb0/express-sharp#2]
setup: follow readme instructions and request my-scale/resize/400
Results: Error: Expected integer between 1 and 16383 for height but received NaN of type number

Looking at sharp, in the resize function, it checks if height is defined, and the parseInt returns a defined number of 0 and thus errors out.

**Comment by pmb0** [comment]
Thanks for reporting. I fixed this issue by letting `height` default to `width`.
