### ISSUE TITLE
How to get orginal size of image?

### ISSUE THREAD

**Issue by hungud** [pmb0/express-sharp#327]
I saw this project code. But I see fix width 500px

resize.dto.ts

`  @Transform(Number)
  @IsNumber()
  @Min(1)
  @Max(10000)
  public width: number = 500`

So I ask how to get orignal image size Eg: 1080px. I guess I must to pass query string w=1080. But I want to get origin w=1080 without pass w=1080

Thank you for this best useful project

**Comment by pmb0** [comment]
Hi, this library aims to scale images for concrete dimensions. Optimizing original images without scaling them is not supported. Yes, you have to pass the `w` parameter. Otherwise the width of the generated image defaults to 500 px.
