### ISSUE TITLE
The aws-sdk dependency is not optional  & support percent sizing 

### ISSUE THREAD

**Issue by bichikim** [pmb0/express-sharp#554]
Hi

Please support scaling

Example

https://abc.com/images/abd.jpg?s=50

50% resizing from original

aws-sdk seems not optional dependency
![image](https://user-images.githubusercontent.com/13829322/131428506-91ec8a7b-06cc-44a0-b3a0-5faa9a9da4ff.png)

Thanks

**Comment by pmb0** [comment]
Hello

Thank you for your feedback. I have just corrected the dependencies (fixed in v4.2.35).

Support for relative scaling is not currently planned -- but you are welcome to provide a pull request for it.

**Comment by reekoz** [comment]
This is still an issue in latest version (4.2.39)

**Comment by robertsLando** [comment]
Confirmed this is still an issue with latest version @pmb0

**Comment by ristomatti** [comment]
They'll need to be completely moved under peerDepencies in addition to marking them as optional.
